apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-memory-stress
  labels:
    app: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      schedulerName: default-scheduler
      containers:
      - name: stress
        image: polinux/stress
        resources:
          limits:
            cpu: "2"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"
        args:
        - "stress"
        - "--cpu"
        - "2" # Number of CPUs to stress
        - "--io"
        - "1" # Number of I/O operations to stress
        - "--vm"
        - "1" # Number of memory allocations to stress
        - "--vm-bytes"
        - "128M" # Amount of memory per allocation

