apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: vj-test-annotation
spec:
  schedulerName: volcano
  minAvailable: 1
  tasks:
    - replicas: 10
      name: "test"
      template:
        metadata:
          annotations:
            volcano.sh/numa-topology-policy: "best-effort"
        spec:
          containers:
            - image: alpine
              command: ["/bin/sh", "-c", "sleep 1000"]
              imagePullPolicy: IfNotPresent
              name: running
              resources:
                limits:
                  cpu: 20
                  memory: "100Mi"
          restartPolicy: OnFailure
