apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mpioutput-hpccptrans-2
  labels:
    type: local
spec:
  #storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/gpfs/bsc_home/xpliu/k8shpcresults/hpccptrans"
  
---

apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: hpccptrans-2
  annotations:
    volcano.sh/task-topology-anti-affinity: "mpiworker"
spec:
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
# Comment out the following section to enable volumes for job input/output.
  volumes:
    - mountPath: "/home"
      #volumeClaimName: "mpi-pvc"
      volumeClaim:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi
  tasks:
    - replicas: 1
      name: mpimaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        metadata:
          annotations:
            volcano.sh/task-priority: "1"
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" "," | sed 's/,/:8,/g'`;
                  MPI_HOST=${MPI_HOST}:8;
                  echo ${MPI_HOST}
                  mkdir -p /var/run/sshd; /usr/sbin/sshd;
                  cp /opt/results/hpccinf.txt /home;
                  sleep 60;
                  mpirun --allow-run-as-root --host ${MPI_HOST} --nooversubscribe --mca mpi_yield_when_idle 0 --mca btl ^openib,uct --mca pml ucx --display-devel-map --display-allocation --report-bindings --npernode 8 -np 16  /opt/HPCC1.5.0-MPI/bin/hpccptrans > hpccptrans-2.log 2>&1;
                  mv hpccoutf.txt hpccptrans-2.out;
              image: mpinetworktrace
              name: mpimaster
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
    - replicas: 2
      name: mpiworker
      template:
        metadata:
          annotations:
            volcano.sh/task-priority: "2"
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  cp /opt/results/hpccinf.txt /home;
                  mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
              image: mpinetworktrace
              name: mpiworker
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 8
                  memory: 40Gi
                limits:
                  cpu: 8
                  memory: 40Gi
          restartPolicy: OnFailure
---
